// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW7ioUDltMPj52lKWTzqrh2oVse3CAlVQ',
    appId: '1:649286349357:web:d16eb2e2295c9cb54fbea4',
    messagingSenderId: '649286349357',
    projectId: 'ambulance-finder-system',
    authDomain: 'ambulance-finder-system.firebaseapp.com',
    databaseURL: 'https://ambulance-finder-system-default-rtdb.firebaseio.com',
    storageBucket: 'ambulance-finder-system.firebasestorage.app',
    measurementId: 'G-8SD30L19J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULWcG9egtrYUvRcktFk07cA3K7zV3h1s',
    appId: '1:649286349357:android:1832611ea5e1e0184fbea4',
    messagingSenderId: '649286349357',
    projectId: 'ambulance-finder-system',
    databaseURL: 'https://ambulance-finder-system-default-rtdb.firebaseio.com',
    storageBucket: 'ambulance-finder-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTOvEKuoYmtrlsn4fT_2r5Zb4YuMTt-8',
    appId: '1:649286349357:ios:6dbeb4342dcdef8f4fbea4',
    messagingSenderId: '649286349357',
    projectId: 'ambulance-finder-system',
    databaseURL: 'https://ambulance-finder-system-default-rtdb.firebaseio.com',
    storageBucket: 'ambulance-finder-system.firebasestorage.app',
    iosBundleId: 'com.example.ambulanceFinderSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfTOvEKuoYmtrlsn4fT_2r5Zb4YuMTt-8',
    appId: '1:649286349357:ios:6dbeb4342dcdef8f4fbea4',
    messagingSenderId: '649286349357',
    projectId: 'ambulance-finder-system',
    databaseURL: 'https://ambulance-finder-system-default-rtdb.firebaseio.com',
    storageBucket: 'ambulance-finder-system.firebasestorage.app',
    iosBundleId: 'com.example.ambulanceFinderSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW7ioUDltMPj52lKWTzqrh2oVse3CAlVQ',
    appId: '1:649286349357:web:2ce3c54a3cb290824fbea4',
    messagingSenderId: '649286349357',
    projectId: 'ambulance-finder-system',
    authDomain: 'ambulance-finder-system.firebaseapp.com',
    databaseURL: 'https://ambulance-finder-system-default-rtdb.firebaseio.com',
    storageBucket: 'ambulance-finder-system.firebasestorage.app',
    measurementId: 'G-LZBZ8M78KC',
  );
}
